gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - graph.yaml
  - index.json
  - index.jsx
  - node_modules
  - package.json
  - scrape.js
  - vendor
  - webpack.config.coffee
  - webpack.config.js
